--- #YAML:1.0
name:               Messaging-Message
version:            1.4
abstract:           message related modules
author:
    - Lionel Cons <lionel.cons@cern.ch>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::MD5:       0
    Encode:            0
    File::Temp:        0
    JSON:              0
    MIME::Base64:      0
    No::Worries:       0.7
    Params::Validate:  0
    POSIX:             0
    Test::More:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
